steps:
  # Step 1: Update package lists
  - name: 'gcr.io/cloud-builders/apt'
    args: ['update']

  # Step 2: Install ffmpeg
  - name: 'gcr.io/cloud-builders/apt'
    args: ['install', '-y', 'ffmpeg']

  # Step 3: Build and submit the container image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/speech-and-text-conversion-api2'

  # Step 4: Deploy the container image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'speech-and-text-conversion-api2'
      - '--image'
      - 'gcr.io/$PROJECT_ID/speech-and-text-conversion-api2'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove this if you want to restrict access

# Set the service account used for deployment
timeout: '900s'  # Set timeout limit for deployment
